FROM hermantolentino/docker-jupyterhub:v5

MAINTAINER herman.tolentino@gmail.com

USER root

ENV NB_USER jupyterhub

RUN \
    rm -rf /var/cache/apt/archives/*.deb && \
    mkdir -p /home/$NB_USER/packages
COPY packages/ /home/$NB_USER/packages/
RUN chmod a+x /home/$NB_USER/packages/*.sh

# Install Python, R and notebook extension packages
RUN bash /home/$NB_USER/packages/python-databases.sh
RUN bash /home/$NB_USER/packages/python-packages.sh
RUN bash /home/$NB_USER/packages/python-gis-packages.sh
RUN bash /home/$NB_USER/packages/python-nlp-packages.sh
RUN bash /home/$NB_USER/packages/download_nltk-data.sh
RUN bash /home/$NB_USER/packages/r-packages.sh
RUN bash /home/$NB_USER/packages/r-gis-packages.sh
RUN bash /home/jupyterhub/packages/ruby-packages.sh

RUN \
    apt-get clean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]
